### ISSUE TITLE
JOB - 일일 신규 가입자 수

### ISSUE THREAD

**Issue by insukL** [ThisisaNiceTeam/this-is-a-nice-backend-batch#4]
# Description
- 일일 단위 신규 가입자 수 계산

# ToDo

- [x] 신규 가입자 수 계산 JOB 생성
  - [x] 신규 가입자 수 집계
  - [x] 연산 결과 File Writer

# ETC
