### ISSUE TITLE
JOB - 일주일 간 활성화 된 유저

### ISSUE THREAD

**Issue by insukL** [ThisisaNiceTeam/this-is-a-nice-backend-batch#7]
# Description
- 일주일 간 활성화 된 유저 집계
- 활성화의 기준은 최소 1회 메시지를 전송 확인

# ToDo

- [x] 일주일 간 활성화 된 유저 집계 JOB 생성
  - [x] 일주일 단위 데이터 집계
  - [x] 연산 결과 File Writer

# ETC
